version: "3.3"
services:
  golang-ci:
    image: 2785/golang-ci:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        dockerfile: "https://github.com/2785/build-images/blob/${GIT_COMMIT}/golang-ci/Dockerfile"
        build_date: ${BUILD_DATE}
